### ISSUE TITLE
Calling `switchy#switch('tabedit', 'sbuf')` twice makes a split, not a tab

### ISSUE THREAD

**Issue by joem** [arp242/switchy.vim#2]
Hi. I was interested in this plugin, so I tried it out, and the first thing I did was tried to call `switchy#switch('tabedit', 'sbuf')` twice in a row, and I was pleased that the on the first call it opened a tab, but then I was surprised when the second call opened a split. This doesn't seem like expected behavior to me. Is there a way to make it always open tabs?

**Comment by joem** [comment]
Oh, nevermind. I just read the documentation and realized the 'sbuf' part was doing that. My bad! lol.

**Comment by arp242** [comment]
I have:

    set switchbuf=useopen,usetab,newtab
    nnoremap <silent> <Leader>a :call switchy#switch('tabedit', 'sbuf')<CR>

And then it always uses a tab, or switches to any active tab.

**Comment by arp242** [comment]
Maybe the example could be better; I, ehm, kind of forgot how all of this works exactly 😅
