### ISSUE TITLE
C Header files

### ISSUE THREAD

**Issue by Konfekt** [arp242/switchy.vim#3]
If not using
```
let ch_syntax_for_h = 1
```
then switchy switches from a header file of a C file to a non-existent Cpp file. 
Since the above is a global option which solves the issue for one repo and creates one for another, how about falling back to a C file?

**Comment by arp242** [comment]
"Fixed" in https://github.com/arp242/switchy.vim/commit/b2b2653937f8b923e1f2b6a7149783fe083d8710

I guess a more complex solution is needed, but I don't use C++, and I think very few people are using this plugin. So I'm okay with this until someone complains/submits a patch.

**Comment by Konfekt** [comment]
Okay, so this expects C++ files to have the extension `.c` ? This looks like it as well  solves the issue for one filetype and creates one for another, but at least it solves a not so urgent rather than a real problem.

**Comment by arp242** [comment]
No, It doesn't support C++. I don't use C++ and I don't feel like spending time to make it work even though it's entirely unclear anyone will ever use it. Happy to merge patches.

**Comment by Konfekt** [comment]
All fine. One solution could be to use a fall-back candidates when the associated file does not exist and there are multiple associated files types, as happens for header files associated with C and C++ files. As things are laid out, it seems that this check goes into each ftplugin for C and C++ https://github.com/arp242/switchy.vim/blob/7ac0657c219c2a5cbfb805150905a7525efd1436/ftplugin/c.vim#L2 where now a header file is first checked and the corresponding existing file is chosen along the lines of

```vim
        \ switchy#has_suffix(bufname(''), '.h')
         \ ? filereadable(bufname('')[:-3] .. '.c' ) ?  bufname('')[:-3] .. '.c' :  bufname('')[:-3] .. '.cpp'
         \ : bufname('')[:-3] .. '.h'}
```

**Comment by arp242** [comment]
I'll test and merge if you send a PR.
